[server]
host = "0.0.0.0"
port = "8080"
readTimeout = "5s"
writeTimeout = "10s"
idleTimeout = "120s"

[logging]
level = "info"
format = "text"

[cors]
allowedOrigins = ["*"]
allowedMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowedHeaders = ["*"]
maxAge = 86400

[gateway]

  [[gateway.routes]]
  path = "/login"
  method = "POST"
  upstreamURL = "http://localhost:8081"
  rewritePath = "/"

